package ru.vadirss.bot.model;

public enum UserState {
    WAIT_CONSENT,
    WAIT_FULLNAME,
    WAIT_PHONE,
    WAIT_TEAM,
    WAIT_POSITION,
    IDLE,

    // Coach flows
    COACH_ANNOUNCE_PICK_TEAM,
    COACH_ANNOUNCE_TEXT,
    COACH_ADD_POOL_CHALLENGE_PICK_TEAM,
    COACH_ADD_POOL_CHALLENGE_TEXT,

    // Admin flows
    ADMIN_TEAMS_MENU,
    ADMIN_CREATE_TEAM_NAME,
    ADMIN_DELETE_TEAM_NUMBER,
    ADMIN_ASSIGN_COACH_PICK_TEAM,
    ADMIN_ASSIGN_COACH_PICK_USER_NUMBER,
    ADMIN_SCHEDULE_PICK_TEAM,
    ADMIN_SCHEDULE_PICK_DAY,
    ADMIN_SCHEDULE_ENTER_TIME,
    ADMIN_ADMINS_MENU,
    ADMIN_ADD_ADMIN_PICK_USER_NUMBER,
    ADMIN_REMOVE_ADMIN_PICK_NUMBER
}
